### ISSUE TITLE
您好，请问可以提供数据集的链接嘛？

### ISSUE THREAD

**Issue by qianyuwu** [Limingxing00/MitoEM2021-Challenge#2]

**Comment by Limingxing00** [comment]
你好,  当时比赛的版本是v1，
[Mitoem-H](https://www.dropbox.com/s/z41qtu4y735j95e/EM30-H-im.zip?dl=0)
[Mitoem-R](https://www.dropbox.com/s/kobmxbrabdfkx7y/EM30-R-im.zip?dl=0)

现在官方把数据集更新到了v2，其中更改了一些手工标注的错误，
[Mitoem-H](https://www.dropbox.com/s/dhf89bc14kemw4e/EM30-H-mito-train-val-v2.zip?dl=0)
[Mitoem-R](https://www.dropbox.com/s/stncdytayhr8ggz/EM30-R-mito-train-val-v2.zip?dl=0)

两个版本的评测分数在这个网址([Here](https://mitoem.grand-challenge.org/evaluation/mitoem/leaderboard/)) 都可以看见。

**Comment by Limingxing00** [comment]
似乎问题已经解决，如果还没有解决，请重新打开这个issue。
